---
- name: Configure Jenkins Infrastructure VM
  hosts: jenkins_servers
  become: yes

  vars:
    docker_image: "neirezcher/spring-petclinic"
    container_name: "spring-petclinic"
    http_port: "8080"

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required system packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python3-pip
        
    - name: Ensure Python is available
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python3)
      changed_when: false
      register: output
      until: output.rc == 0
      retries: 3
      delay: 5

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Pull Docker image
      docker_image:
        name: "{{ docker_image }}"
        source: pull
        force_source: no

    - name: Run Docker container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        restart: yes
        ports:
          - "{{ http_port }}:8080"